export const EVENTS = {
  CREATE_ROOM: 'createRoom',
  JOIN_ROOM: 'joinRoom',
  LEAVE_ROOM: 'leaveRoom',
  LIST_ROOMS: 'listRooms',
  ROOMS_LIST: 'roomsList',
  CONNECTION: 'connection',
  JOIN: 'join',
  SET_READY: 'setReady',
  MINE: 'mine',
  HIRE_WORKER: 'hireWorker',
  SPAWN_UNIT: 'spawnUnit',
  DISCONNECT: 'disconnect',

  LOBBY_UPDATE: 'lobbyUpdate',
  GAME_START: 'gameStart',
  RESOURCE_UPDATE: 'resourceUpdate',
  UNIT_UPDATE: 'unitUpdate',
  SPAWN_ENEMIES: 'spawnEnemies',
  SPAWN_UNITS: 'spawnUnits',
  STATE_UPDATE: 'stateUpdate',
  GAME_OVER: 'gameOver',
};
